### ISSUE TITLE
希望添加挖宝的转盘和开门的结果预报

### ISSUE THREAD

**Issue by qwx** [thewakingsands/matcha#1]
因为挖宝转盘总是跳来跳去，让我这个挖宝人太过痛苦，希望添加语音播报（或者有更好的形式？）当前转盘或开门的情况。
当然我不白嫖，已经分析了opcode并且对matcha改了一下，自己测试还ok，希望大大重新梳理一下加到matcha里。下面是详情：
以国服5.5版本为基础，仅适用于G12，绿图的那个没测过。
宝殿转盘：
opcode：0x013D
数据部分我直接贴测试的代码，因为太丑就不提pr了，希望大佬整理
```int i = 0;
                i = (int)BitConverter.ToUInt32(data, 40);
                if (i == 193)
                {
                    Output.SendTTS("上级");
                }
                else if (i == 191)
                {
                    Output.SendTTS("下级");
                }
                else if (i == 192)
                {
                    Output.SendTTS("中级");
                }
                else if (i == 194)
                {
                    Output.SendTTS("叹号");
                }
                else if (i == 195)
                {
                    Output.SendTTS("白金");
                }
                else if (i == 196)
                {
                    Output.SendTTS("结束");
                }
```
清道夫：
实话实说我没找到对应的opcode，而且对于清道夫劈死后的那个出的新的结果我也没找到，但是我在ActorControlSelf里面找了个跟霹雷相关的，但是切换地图的时候也有可能触发，所以我觉得我应该是监控了什么奇奇怪怪的东西，姑且放上来。
```
                    case ActorControlType.Thunder:
                        {
                            int c = (int)BitConverter.ToUInt16(data, 2);
                            if (c == 0)
                            {
                                Output.SendTTS("雷");
                            }
                            else if (c == 57344)
                            {
                                Output.SendTTS("无");
                            }

                            break;
                        }
```
这里的Thunder是236
希望大佬能找到，或者限制一下触发的地图

宝境河流：
opcode：0x0273
代码：
```
                i = (int)BitConverter.ToUInt32(data,16);
                if (i == 71838723)
                {
                    int c = (int)BitConverter.ToUInt32(data, 40);
                    if (c == 1)
                    {
                        Output.SendTTS("冲呀");
                    }
                    else if (c == 0)
                    {
                        Output.SendTTS("结束");
                    }
                }
```
感谢本项目对开源社区及FF14做出的贡献，如果大佬觉得不适合做到插件中，可以直接关闭，谢谢！

**Comment by qwx** [comment]
除了清道夫的不怎么稳定外，开门和转盘已经经历过3个版本的考验了。

**Comment by zhyupe** [comment]
**梦羽宝殿**

TreasureShiftingWheelResult
https://github.com/zhyupe/FFXIV-Packet-Dissector/blob/fc634e0b12ea674a5cd2eac284d5127aef03f038/tools/json/TreasureShiftingWheelResult.json

ActorControl -- Type 413 (EObjAnimation), Object Id 2007457
|Id|#|Level|Data0|Data1|Category|
|--|--|-----|--- | --|----|
|10fcd|0|8508168|16384(4000)|16386(4002)|Gold|
|10fcc|1|8508169|1024(0400)|1026(0402)|Out|
|10fcb|2|8508170|16(0010)|18(0012)|Low|
|10fca|3|8508171|1024(0400)|1026(0402)|Out|
|10fc9|4|8508172|64(0040)|66(0042)|Medium|
|10fc8|5|8508173|1024(0400)|1026(0402)|Out|
|10fc7|6|8508174|256(0100)|258(0102)|High|
|10fc6|7|8508175|1024(0400)|1026(0402)|Out|
|10fc5|8|8508176|16(0010)|18(0012)|Low|
|10fc4|9|8508177|1024(0400)|1026(0402)|Out|
|10fc3|10|8508178|4096(1000)|4098(1002)|Silver|
|10fc2|11|8508179|1024(0400)|1026(0402)|Out|

**Comment by zhyupe** [comment]
闪电没有找到稳定的预报方式，暂不加入；
转盘预报和开门预报（包括 G10）已经添加
