### ISSUE TITLE
抹茶物价查询页面可以分别显示hq和nq的价格吗

### ISSUE THREAD

**Issue by yuhahu** [thewakingsands/matcha#10]
当前版本删除了基础材料的hq品质,每次使用物价查询时都会同时显示nq和hq两行,很占用游戏界面空间,要经常拖动或缩小插件页面和包裹等系统页面.
本身插件已经可以切换nq+hq与单独显示hq价格,是否可以通过修改配置文件使得默认查询页面只显示一行nq价格以节省页面空间,
如果不能通过修改配置实现,是否可以修改插件,使得不点击hq按钮时只显示一行nq物品价格,点击hq按钮后只显示hq一行.

谢谢查看,联系方式:yuhahuan@gmail.com

**Comment by zhyupe** [comment]
物价显示的两行不是 NQ 和 HQ，是最低价和购买多个（从最低价起算，直至可购买大于等于 99 个的价格）时的平均价格。每行后面括号标注的是该价格下可获取的 NQ/HQ 物品数量。
