### ISSUE TITLE
关于act的问题，不知道应该在哪提这个issues

### ISSUE THREAD

**Issue by WSMTBG** [thewakingsands/matcha#23]
![b33aa75971e10b3f504ced751f60e08d](https://github.com/user-attachments/assets/3a7acad2-0d12-49fe-9582-10c29af85563)
今天cx（FFXIV_ACT_CutsceneSkip）报错这个，cafe和呆萌都是这个问题...或者和我说下这个应该去哪儿反馈谢谢

**Comment by oott123** [comment]
off topic.

找插件作者。
