### ISSUE TITLE
关于ACT抹茶查价显示在税前税后反复跳跃情况的反馈

### ISSUE THREAD

**Issue by 112Yanyouxue** [thewakingsands/matcha#3]
尊敬的制作团队
       你们好，非常感谢贵方提供了这样一个特别便利的ACT查价小工具，但是在某次更新后，价格显示会同时显示不同服务器加税后和加税前的价格，因为有的服务器是税前，有的是税后，导致比较标准无法统一，使用起来增加了一点点阻碍，经过长期斟酌，所以在一个路人朋友提供的地址下，我来到这里注册并反映了这样一个问题。如果可以的话，个人觉得最好是统一显示或者只有税前，或者只有税后，这两种其中之一的价格，最好不要两者在不同服务器之间混淆。
        希望各位优秀的制作人员能够在百忙之中浏览到我这份表述可能不甚详细的建议，如果觉得这个建议值得研究，并在后续更新作出新的改动，就不胜感激之至了，当然对以往通过这个工具获得的方便，我也会在这里对制作团队表示诚挚的尊敬和谢意。
        非常感谢！！ 
                                                                                                                                                                            一名普通的FF14玩家
                                                                                                                                                                                   来自    中国

**Comment by zhyupe** [comment]
已修复
