### ISSUE TITLE
6.01更新后看不见播报（钓鱼、进本等）

### ISSUE THREAD

**Issue by crosspedestrian** [thewakingsands/matcha#6]
ACT国服整合+解析插件+抹茶+延迟显示+高级触发器+悬浮窗插件+cactbot
钓鱼、进本时未发送系统通知，测试按钮正常

相关日志：
[E][System.IO.EndOfStreamException]无法在流的结尾之外进行读取。
   在 System.IO.__Error.EndOfFile()
   在 System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   在 System.IO.BinaryReader.ReadUInt32()
   在 _aC._TD(Byte[] )
   在 _Bd._we(_CC , Byte[] )
   在 _Bd._8d(_CC , Byte[] )
   在 _ae._D(_CC , Byte[] )
   在 _IC._lC(Byte[] )
   在 _IC._Ab(Byte[] )
   在 _IC._iC(String , Int64 , Byte[] )

**Comment by oott123** [comment]
等更新
