### ISSUE TITLE
钓鱼“中杆” TTS 问题

### ISSUE THREAD

**Issue by oott123** [thewakingsands/matcha#7]
百度或者微软会读成 zhong4

也许输出 TTS 需要挑一个别的同音字

**Comment by zhyupe** [comment]
Fixed in 2dc2b7c

**Comment by lynxpic** [comment]
现在播报是普通杆 强力杆，我想改回中杆和重杆怎么做呢

**Comment by oott123** [comment]
@Koriyuka 可以用 FoxTTS 插件的文本替换功能替换。
