### ISSUE TITLE
希望增加抹茶插件里仙人微彩功能

### ISSUE THREAD

**Issue by Ventulus-lab** [thewakingsands/matcha#8]
就是抹茶插件里的仙人微彩功能，能不能像https://g.nga.cn/read.php?tid=14587834 这个帖子里一样，给出每一步的推荐挖开哪个格子

**Comment by TundraWork** [comment]
抹茶在很久前即拥有此功能，请确保抹茶运行正常且抹茶ngld悬浮窗显示正常，然后游玩仙人微彩，抹茶悬浮窗中将自动显示下一步推荐。

**Comment by zhyupe** [comment]
请到悬浮窗项目中跟进
