### ISSUE TITLE
Windows8.1无法显示Toast通知

### ISSUE THREAD

**Issue by NicoOrz** [thewakingsands/matcha#9]
在8.1系统下抹茶无法正常弹出通知 无论是托盘气泡还是Toast 只有TTS播报

**Comment by zhyupe** [comment]
通知是使用 Windows 10 API 实现的，Windows 8 需要使用其他方案。考虑到 Windows 8 将在 23 年 1 月停止支持，且调试环境配置较为繁琐，没有计划支持。
